# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "609fe9f27b2b83ab7a3b8273a8041f86"
name = "order-app"
handle = "order-app-79"
application_url = "https://loose-efficiently-proper-advancement.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers,unauthenticated_read_customers,read_orders,read_fulfillments,write_order_edits,read_order_edits,read_shipping,write_shipping,read_locations,unauthenticated_read_customer_tags"

[auth]
redirect_urls = [
  "https://loose-efficiently-proper-advancement.trycloudflare.com/auth/callback",
  "https://loose-efficiently-proper-advancement.trycloudflare.com/auth/shopify/callback",
  "https://loose-efficiently-proper-advancement.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false

[build]
dev_store_url = "chcekout-extension.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
